### ISSUE TITLE
moment

### ISSUE THREAD

**Issue by inteldork** [CometSb/CometSiteApi#1]
![image](https://github.com/CometSb/CometSiteApi/assets/61995036/63261d96-2e28-43a6-8401-65c78d553c84)

**Comment by CometSb** [comment]
Why would we make your endpoint public?

**Comment by inteldork** [comment]
idk, its still an endpoint tho

**Comment by CometSb** [comment]
> idk, its still an endpoint tho

True. We might.

**Comment by inteldork** [comment]
i luv men
